Medication dev
Yury03/MedsTime pull request #9
Opened 2023-08-05 12:41 UTC by Yury03

medication fragment completed

2023-08-05 12:43 UTC, Yury03 commented on app/src/main/java/com/example/medstime/data/MedicationContractImpl.kt
# was inserted placeholder

2023-08-06 22:01 UTC, BadLog1n requested changes

2023-08-06 22:01 UTC, BadLog1n commented on app/src/main/java/com/example/medstime/data/MedicationContractImpl.kt
> +//    ).build()//todo убрать из Main Thread
Наверное не стоит нести в прод комменты, забудем убрать потом

2023-08-06 22:01 UTC, BadLog1n commented on app/src/main/java/com/example/medstime/ui/medication/MedicationFragment.kt
> +                context?.let { it1 -> TimesListAdapter(it, it1, medicationClick) }
Вот здесь наверное лучше it1 явно указать

2023-08-06 22:01 UTC, BadLog1n commented on app/src/main/java/com/example/medstime/ui/medication/MedicationFragment.kt
> +
Этот кусок удали, у нас уже новый формат меню

2023-08-06 22:01 UTC, BadLog1n commented on app/src/main/java/com/example/medstime/ui/medication/MedicationViewModel.kt
> +    @RequiresApi(Build.VERSION_CODES.O)//TODO
Подними наверное сразу версию андроида, чего тянуть

2023-08-06 22:01 UTC, BadLog1n commented on app/src/main/res/drawable/bottom_left_radius.xml
> +        android:bottomLeftRadius="25dp"
лучше используй значения, кратные 8, то есть 24

2023-08-06 22:01 UTC, BadLog1n commented on app/src/main/res/drawable/bottom_right_radius.xml
> +        android:bottomRightRadius="25dp"
Здесь и далее

2023-08-06 22:01 UTC, BadLog1n commented on app/src/main/res/values/colors.xml
> +    <color name="alert_dialog">#F0F1F5</color>
Лучше мне кажется назвать какой это цвет, а то вообще не понятно
Если хочешь указать, что это прям алерт, то сделай отступ, добавь коммент сверху или в название это добавь цвет, чтобы понятно было

2023-08-06 22:01 UTC, BadLog1n commented on gradle/wrapper/gradle-wrapper.properties
>  distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip
Вот это стоит удалить и в дальнейшем настроить гитигнор

2023-08-23 22:57 UTC, merged